[package]
name = "dd_overdrive"
version = "0.1.0"
authors = ["Rob Saunders <rob@wearebrandnew.com>"]

[dependencies]
vst2 = { git = "https://github.com/rust-dsp/rust-vst" }

[lib]
name = "dd_overdrive"
crate-type = ["cdylib"]
